### ISSUE TITLE
[feat] PKCanvasView 기본 기능 구현

### ISSUE THREAD

**Issue by dorachoii** [DeveloperAcademy-POSTECH/2024-MC3-A03-Sgrr#13]
## Description

PKCanvasView에 이미지를 넣고 그 위에 펜으로 그림을 그릴 수 있는 기능을 구현하겠습니다.
이후에 이것을 CGImage로 뽑아 케이크 메테리얼로 입히는 작업을 수행할 예정입니다.

## To-do

- [x] PKCanvas 기본 기능 구현(그리기, 지우기 등)
- [x] PKCanvas에 이미지 추가하기
- [x] PKCanvas에 이미지 추가한 뒤 그 위에 그림 그리기
