### ISSUE TITLE
[feat] 3D 모델뷰 띄우기

### ISSUE THREAD

**Issue by dorachoii** [DeveloperAcademy-POSTECH/2024-MC3-A03-Sgrr#3]
## Description

모델을 비추는 카메라의 각도를 수정하고, 확대, 축소, 회전의 기능을 추가하겠습니다.

## To-do

- [x] 카메라 각도 수정하기
- [x] 멀티 터치로 모델 확대 축소 하기
- [x] 드래그로 모델 회전시키기
