### ISSUE TITLE
[fix] FinalGuideView에 연결한 element 데이터 로직 변경, Sgrr Entity 수정, 그 외 대공사

### ISSUE THREAD

**Issue by onesunny2** [DeveloperAcademy-POSTECH/2024-MC3-A03-Sgrr#58]
## Description

> 그저 대공사일 뿐...

## To-do

- [x] Sgrr 모델에 Entity 수정 (기존 elementKeyword를 top, side로 구분)
- [x] Cake 클래스, CoredataManager도 같이 수정
- [x] ComponentView 코드 최신버전으로 수정 (카톡으로 받은 티나 코드)
- [ ] 컨셉, 요소 컴포넌트 쪼개기
- [ ] 요소 내에서 요소에 따른 로직 수정하기
