### ISSUE TITLE
[feat] 색상, 컨셉, 요소 1개를 채우지 않으면 버튼이 비활성화된다

### ISSUE THREAD

**Issue by gorgeouseowoo** [DeveloperAcademy-POSTECH/2024-MC3-A03-Sgrr#65]
<-- [prefix] 한국어 설명-->

## Description

색상, 컨셉, 요소 1개를 채우지 않으면 버튼이 비활성화된다

## To-do

- [ ] 색상 정보 필수 입력
- [ ] 컨셉 정보 필수 입력
- [ ] 요소 정보 필수 입력
