### ISSUE TITLE
[fix] coredataManager 및 Entity 구조 전원 변경 후 첫 연결 작업

### ISSUE THREAD

**Issue by onesunny2** [DeveloperAcademy-POSTECH/2024-MC3-A03-Sgrr#67]
## Description

> coredataManager 및 Entity 구조 전원 변경 후 첫 연결 작업

## To-do

- [x] Entity 변경
- [x] New CoredataManager 추가
- [x] 기존 매니저 주석
- [x] App 부분 코드 수정
- [x] Cake 모델 수정
