### ISSUE TITLE
[design] Button 그림자 삭제, 파이널가이드뷰 칼라 그림자 삭제, 텍스트 필드 간격 조정

### ISSUE THREAD

**Issue by gorgeouseowoo** [DeveloperAcademy-POSTECH/2024-MC3-A03-Sgrr#70]
<-- [prefix] 한국어 설명-->

## Description

설명을 작성하세요.

## To-do

- [ ] Button 그림자 삭제
- [ ] 파이널가이드뷰 칼라 그림자 삭제
- [ ] 텍스트 필드 간격 조정
