### ISSUE TITLE
[feat] 배경, 레터링 색상을 추가하는 기능 구현

### ISSUE THREAD

**Issue by gorgeouseowoo** [DeveloperAcademy-POSTECH/2024-MC3-A03-Sgrr#8]
<-- [prefix] 한국어 설명-->

## Description

칼라피커를 이용해 원하는 색상을 선택합니다

## To-do

- [ ] 색상 선택
- [ ] 선택한 색상에 따른 hex 코드 보여주기
- [ ] 선택한 색상이 동그라미에 채워지기
- [ ] 색상 변경
- [ ] 컬러뷰 UI 그리기
- [x] 빙수먹기
